# Default values for alc-collect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

image:
  registry: docker.io
  pullPolicy: IfNotPresent
  app:
    registry: # defaults to image.registry
    tag: "" # overrides the image tag whose default is the chart appVersion.
    pullPolicy: # defaults to image.pullPolicy
  liquibase:
    registry: # defaults to image.registry
    tag: 2.4.0
    pullPolicy: # defaults to image.pullPolicy

imagePullSecrets: []

env:
  type: "" # possible values: dev, test, preprod, prod
  label: ""

datasource:
  host: ""
  port: ""
  dbName: ""
  user: ""
  globalSchemaPrefix: "wo"
  connTimeout: 60000
  maxPoolSize: 2
  minIdle: 0

liquibase:
  enabled: true
  syncOnly: false
  user: ""
  role: ""
  replicationRole: ""

members:
  - businessUnit: ""
    applicationMember: ""
    memberSign: ""
    liquibase:
      # user: ""
      # password: ""
      role: ""
      replicationRole: ""
    datasource:
      globalSchema: false
      host: ""
      port: ""
      dbName: ""
      user: ""
      password: ""
      connTimeout: ""
      maxPoolSize: ""
      minIdle: 0

kafka:
  user: ""
  servers: ""
  saslMechanism: PLAIN
  securityProtocol: SASL_SSL
  schemaRegistry:
    credSource: USER_INFO
    user: ""
    url: ""
  topics:
    personstructure:
      name: hr.vestigo.hp.personstructure
      consumerGroup: hr.vestigo.hp.personstructure
    limitbucket:
      name: hr.vestigo.hp.limitbucket
      consumerGroup: hr.vestigo.hp.limitbucket
    limitbucketh:
      consumerGroup: hr.vestigo.hp.limitbucketh
    authptragrmtlim:
      name: hr.vestigo.hp.authptragrmtlim
      consumerGroup: hr.vestigo.hp.authptragrmtlim
    limitdef:
      name: hr.vestigo.hp.limitdef
      consumerGroup: hr.vestigo.hp.limitdef
    expiredauth:
      name: hr.vestigo.hp.expiredauth
      consumerGroup: hr.vestigo.hp.expiredauth
    matchedauth:
      name: hr.vestigo.hp.matchedauth
      consumerGroup: hr.vestigo.hp.matchedauth

oauth2:
  enabled: false
  resourceUri: ""

timezone: ""

secret:
  decryptionKey: ""
  datasourcePassword: ""
  kafkaPassword: ""
  kafkaSchemaRegistryPassword: ""
  liquibasePassword: ""
  trustStorePassword: ""
  keyStorePassword: ""

logger:
  logToFile: false
  rollingFileAppender: false
  logDir: "/var/log/app"
  logDirMount:
    enabled: false
    # spec:
      # emptyDir: {}
      # flexVolume:
        # driver: ""
        # fsType: ""
        # options:
          # basepath: ""
          # basename: ""

healthStatusDownReturnCode: "418"

javaOpts: "-Xms256M -Xmx256M"

springActiveProfile: "prod"

podAnnotations: {}

deploymentAnnotations: {}

serviceAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext: {}

service:
  enabled: true
  type: ClusterIP
  port: 8443
  nodePort: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}
  labels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

initContainers: []

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - alc-collect
          topologyKey: kubernetes.io/hostname

deployment:
  replicaCount: 1
  annotations: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  terminationGracePeriodSeconds: 60
  restartPolicy: Always
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 2
    httpGet:
      path: /health/readiness
      port: http
      scheme: HTTPS
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 3
    httpGet:
      path: /health/liveness
      port: http
      scheme: HTTPS

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

mountServerCertFromSecret:
  enabled: false
  secretName: ""
  certPath: ""
  keyPath: ""

mountKeyStoreFromSecret:
  enabled: false
  secretName: ""
  keyStoreName: ""
  keyStoreType: JKS

mountTrustStoreFromSecret:
  enabled: false
  secretName: ""
  trustStoreName: ""
  trustStoreType: JKS

mountCaFromSecret:
  enabled: false
  secretName: ""

customVolumes: []

customMounts: []

customEnv: []
