{{- if .Values.oAuth2.enabled -}}
api:
  gateway:
    authentication: oauth2
{{ "" }}
{{- end }}
spring:
  {{- if .Values.oAuth2.enabled }}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {{ required "Please specify oAuth2 URI in oAuth2.resourceUri" .Values.oAuth2.resourceUri }}
  {{- end }}
  cloud:
    gateway:
      routes:
        - id: alc_route
          predicates:
            - Path=/alc-collect/**
          uri: https://{{ required "ALC collect application service name has to be defined in routes.alcCollect.serviceName" .Values.routes.alcCollect.serviceName }}:{{ required "ALC collect application port number has to be defined in routes.alcCollect.servicePortNumber" .Values.routes.alcCollect.servicePortNumber }}
          filters:
            - StripPrefix=1
        - id: auth-limit-control_route
          predicates:
            - Path=/auth-limit-control/**
          uri: https://{{ required "Auth limit control application service name has to be defined in routes.authLimitControl.serviceName" .Values.routes.authLimitControl.serviceName }}:{{ required "Auth limit control application port number has to be defined in routes.authLimitControl.servicePortNumber" .Values.routes.authLimitControl.servicePortNumber }}
          filters:
            - StripPrefix=1
        - id: person-structure-ms_route
          predicates:
            - Path=/person-structure/**
          uri: https://{{ required "Person structure application service name has to be defined in routes.personStructure.serviceName" .Values.routes.personStructure.serviceName }}:{{ required "Person structure application port number has to be defined in routes.personStructure.servicePortNumber" .Values.routes.personStructure.servicePortNumber }}
          filters:
            - StripPrefix=1
