apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-liquibase-configmap
data:
  changelog.yaml: |-
    {{ include "product-factory.changelog" . | nindent 4 }}
  liquibase.properties: |-
    {{ include "product-factory.liquibase-config" . | nindent 4 }}